---
config:
    xyChart:
        width: 60
        height: 15
        xAxis:
          showTitle: false
          showLabel: false
          showAxisLine: false
          showTick: false
        yAxis:
          showTick: false
          showTitle: false
          showLabel: false
          showAxisLine: false

    themeVariables:
        xyChart:
            backgroundColor: transparent
            plotColorPalette: "#0D74E6"
---
xychart-beta
    %%rates