---
config:
    xyChart:
        width: 900
        height: 400
        xAxis:
          tickLength: 5
          tickWidth: 1
        yAxis:
          tickLength: 5
          tickWidth: 1

    themeVariables:
        xyChart:
            titleColor: "#4492F9"
            backgroundColor: transparent 
            plotColorPalette: "#0D74E6"
---
xychart-beta
    %%title
    %%date
    %%downloads
    x-axis "Date" [1,2,3]
    y-axis "Downloads" line [1,2]